name: CI build action

on:
  workflow_dispatch:
  push:
    branches:
      - ci-test/**
      - gh-readonly-queue/main/**

jobs:
  hello:
    runs-on: kabbage-default
    steps:
    - run: echo "🎉 This job uses runner scale set runners!"

  docker:
    name: Test on docker
    runs-on:
      - kabbage-dind
    container:
      image: ghcr.io/wolfi-dev/sdk:latest@sha256:26f510522abb4923875e8424c611e41cdf5fd017117f1a88e234ec2f8da6a25c
      options: |
        --cap-add NET_ADMIN --cap-add SYS_ADMIN --security-opt seccomp=unconfined --security-opt apparmor:unconfined

    steps:
      - uses: actions/checkout@v3

      - name: 'Trust the github workspace'
        run: |
          # This is to avoid fatal errors about "dubious ownership" because we are
          # running inside of a container action with the workspace mounted in.
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: 'Generate local signing key'
        run: |
          make MELANGE="melange" local-melange.rsa

      - name: 'Build'
        run: |
          make BUILDWORLD=no package/binutils

  k8s:
    name: Test on k8s
    runs-on:
      - kabbage-k8s
    container:
      image: ghcr.io/wolfi-dev/sdk:latest@sha256:26f510522abb4923875e8424c611e41cdf5fd017117f1a88e234ec2f8da6a25c
      options: |
        --cap-add NET_ADMIN --cap-add SYS_ADMIN --security-opt seccomp=unconfined --security-opt apparmor:unconfined
    steps:
      - uses: actions/checkout@v3

      - name: 'Trust the github workspace'
        run: |
          # This is to avoid fatal errors about "dubious ownership" because we are
          # running inside of a container action with the workspace mounted in.
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: 'Generate local signing key'
        run: |
          make MELANGE="melange" local-melange.rsa

      - name: 'Build'
        run: |
          make BUILDWORLD=no package/binutils

