name: Actions Runner Controller Demo
on:
  workflow_dispatch:

jobs:
  Explore-GitHub-Actions:
    # You need to use the INSTALLATION_NAME from the previous step
    runs-on: kabbage-default
    steps:
    - run: echo "🎉 This job uses runner scale set runners!"
